GL_CAMERAS: |
  - name: Door Lock Camera
    input_type: rtsp
    id: 
      rtsp_url: ""
    options:
      crop:
        relative:
          top: .1
          bottom: .9
          left: .1
          right: .9