GL_CAMERAS: |
  - name: Door Lock Camera
    input_type: rtsp
    id: 
      rtsp_url: rtsp://admin:VvsVisGyy3bznLJB@10.44.2.95:554
    options:
      crop:
        relative:
          top: .1
          bottom: .9
          left: .1
          right: .9